### ISSUE TITLE
Activity previews in the Recents overview are displayed incorrectly

### ISSUE THREAD

**Issue by vladimiroltean** [Lenovo-YTX703-Devel/android_device_lenovo_YTX703-common#13]
The activities that were opened when the tablet is in portrait mode have previews that are rotated by 90 degrees.
The activities that where opened with the tablet in landscape mode are stretched to 50% of the preview's height, and the upper half of the preview is black.

**Comment by Gabriel85** [comment]
Sounds like a upstream issue to me, can't remember seeing anything like that with LOS 14.1. Although, I use the tablet 99% of the time in landscape..

**Comment by vladimiroltean** [comment]
Issue is due to broken implementation of the `ro.sf.hwrotation` property.
Fixed through this patchset: https://review.lineageos.org/#/c/LineageOS/android_frameworks_native/+/221925/
