### ISSUE TITLE
Rework device trees to use more Open-Source alternatives to BLOBs

### ISSUE THREAD

**Issue by Quallenauge** [Lenovo-YTX703-Devel/android_device_lenovo_YTX703-common#19]
_From @Quallenauge on February 2, 2018 12:9_

It seems the sony developers does a good job at handling their devices.
Take these trees (device/vendor) as template for the lenovo devices.
The device, which is closest to our device, seems the device-sony-**tone**.

_Copied from original issue: Quallenauge/Yoga-Tab-3-Plus-Issue-Tracker#4_

**Comment by Quallenauge** [comment]
_From @Gabriel85 on February 16, 2018 13:11_

Open Source Power HAL (current blob not really working):
https://github.com/sonyxperiadev/device-sony-common/tree/master/hardware/power
https://github.com/sonyxperiadev/device-sony-common/tree/master/hardware/librqbalance

OS Sensor HAL (maybe incompatible with some of our sensors):
https://github.com/LineageOS/android_hardware_sony_DASH

OS Thermal Manager (needs new xml configs written, and maybe kernel-patches):
https://github.com/LineageOS/android_hardware_sony_thermanager

OS Location APIs (not sure if that is a substitute for some of our blobs?)
https://github.com/LineageOS/android_vendor_qcom_opensource_location/

Is there other useful stuff?

**Comment by vladimiroltean** [comment]
I'm not entirely sure what were the actionable items here. Closing.
