### ISSUE TITLE
Reduce DT2W power consumption in sleep

### ISSUE THREAD

**Issue by Quallenauge** [Lenovo-YTX703-Devel/android_device_lenovo_YTX703-common#23]
_From @vladimiroltean on February 18, 2018 16:28_

Proposed solution: search the iio subsystem (accelerometer sensor) for a device with wakeup irq to hook into. Disable the dt2w driver after a period of idle time, and then use the accelerometer's irq to re-enable dt2w.

_Copied from original issue: Quallenauge/Yoga-Tab-3-Plus-Issue-Tracker#16_

**Comment by Quallenauge** [comment]
_From @Gabriel85 on February 18, 2018 17:37_

That wouldn't save any power if it's in a backpack or so. But the accelerometer could be used for the complete detection, although I never have seen another implementation of this.

**Comment by vladimiroltean** [comment]
This is not feasible and I'm not gonna do it.

**Comment by Gabriel85** [comment]
Well it is, but kind of pointless. If somebody would be able to get kernel-access to the accelerometer, I could easily implement proper hardware DT2W. The accelerometer supports that officially, there is even already some code for that in the current kernel. I just don't understand yet, how the sensor userspace-stuff is able to communicate with the accelerometer, without the kernel. I guess there is some special low-level qualcom API module in the kernel, which allows that.
