### ISSUE TITLE
Test: Bring up lineage-15.1

### ISSUE THREAD

**Issue by Quallenauge** [Lenovo-YTX703-Devel/android_device_lenovo_YTX703-common#25]
_From @Quallenauge on February 2, 2018 10:45_

It should be tested:

The current firmware is able to launch at the device.
The current firmware should not have device specific errors (like missing firmware / configuration files, which are available for the L-version).

_Copied from original issue: Quallenauge/Yoga-Tab-3-Plus-Issue-Tracker#1_

**Comment by Quallenauge** [comment]
_From @vladimiroltean on February 26, 2018 20:17_

Is there anything left to do here?

**Comment by Quallenauge** [comment]
Actually it needs to be tested on a F device. After that, I think we can close this issue.

**Comment by vladimiroltean** [comment]
Should I buy one?

**Comment by vladimiroltean** [comment]
I bought one. It works.
