### ISSUE TITLE
Build a vendor image

### ISSUE THREAD

**Issue by vladimiroltean** [Lenovo-YTX703-Devel/android_device_lenovo_YTX703-common#30]
Treble compatibility requires that we dedicate a partition for userspace hardware support libraries and binaries. Let's use this thread to discuss our possibilities.
What we know so far:

* The device's partition table:
```
Number  Start (sector)    End (sector)  Size       Code  Name                                                                                                            [10/116]
   1          131072          303103   84.0 MiB    0700  modem                                                                                                                   
   2          393216          393217   1024 bytes  FFFF  fsc                                                                                                                     
   3          393218          393233   8.0 KiB     FFFF  ssd                                                                                                                     
   4          393234          394257   512.0 KiB   FFFF  sbl1                                                                                                                    
   5          394258          395281   512.0 KiB   0700  sbl1bak                                                                                                                 
   6          395282          396305   512.0 KiB   FFFF  rpm                                                                                                                     
   7          396306          397329   512.0 KiB   0700  rpmbak                                                                                                                  
   8          397330          401425   2.0 MiB     FFFF  tz                                                                                                                      
   9          401426          405521   2.0 MiB     0700  tzbak                                                                                                                   
  10          405522          406033   256.0 KiB   FFFF  devcfg                                                                                                                  
  11          406034          406545   256.0 KiB   FFFF  devcfgbak
  12          406546          439313   16.0 MiB    0700  dsp
  13          439314          442385   1.5 MiB     FFFF  modemst1
  14          442386          445457   1.5 MiB     FFFF  modemst2
  15          524288          524351   32.0 KiB    FFFF  DDR
  16          524352          527423   1.5 MiB     FFFF  fsg
  17          527424          527455   16.0 KiB    FFFF  sec
  18          655360          677887   11.0 MiB    FFFF  splash
  19          786432          788479   1024.0 KiB  FFFF  aboot
  20          788480          790527   1024.0 KiB  0700  abootbak
  21          790528          921599   64.0 MiB    FFFF  boot
  22          921600         1052671   64.0 MiB    FFFF  recovery
  23         1052672         1054719   1024.0 KiB  FFFF  devinfo
  24         1179648         1245183   32.0 MiB    FFFF  userstore
  25         1310720         8650751   3.5 GiB     FFFF  system
  26         8650752         9175039   256.0 MiB   FFFF  cache
  27         9175040         9240575   32.0 MiB    FFFF  persist
  28         9240576         9242623   1024.0 KiB  FFFF  misc
  29         9242624         9243647   512.0 KiB   FFFF  keystore
  30         9243648         9243711   32.0 KiB    FFFF  config
  31         9243712         9374783   64.0 MiB    FFFF  oem
  32         9437184         9437247   32.0 KiB    FFFF  limits
  33         9568256         9569279   512.0 KiB   FFFF  mota
  34         9569280         9571327   1024.0 KiB  FFFF  dip
  35         9571328         9636863   32.0 MiB    FFFF  mdtp
  36         9636864         9637887   512.0 KiB   FFFF  syscfg
  37         9637888         9646079   4.0 MiB     FFFF  mcfg
  38         9699328         9700095   384.0 KiB   FFFF  cmnlib
  39         9700096         9700863   384.0 KiB   FFFF  cmnlibbak
  40         9700864         9701631   384.0 KiB   FFFF  cmnlib64
  41         9701632         9702399   384.0 KiB   FFFF  cmnlib64bak
  42         9702400         9702911   256.0 KiB   FFFF  keymaster
  43         9702912         9703423   256.0 KiB   FFFF  keymasterbak
  44         9830400         9830911   256.0 KiB   FFFF  apdp
  45         9830912         9831423   256.0 KiB   FFFF  msadp
  46         9831424         9831439   8.0 KiB     FFFF  dpo
  47         9831440         9833487   1024.0 KiB  FFFF  userencrypt
  48         9833488         9845775   6.0 MiB     FFFF  countrycode
  49         9845776        61071326   24.4 GiB    FFFF  userdata
```

The current size requirements of our hardware support libraries:
```
$ du -sh out/target/product/YTX703L/system/vendor/
257M    out/target/product/YTX703L/system/vendor/
```

Currently the only possibility I see is to use a composite vendor partition, with partition 26 (cache - 256MB) as main and partition 31 (oem - 64MB) as secondary. Init scripts will take care that the secondary vendor partition is mounted inside the primary one.
The issue I see currently is that I'm not sure what support AOSP has for composite vendor partitions (it needs to be able to flash a vendor.img file).

**Comment by vladimiroltean** [comment]
Alternatively we can work to trim down the libraries inside vendor.img to fit inside a 256MB partition. I'm not sure whether that's actually a good idea in the long run.

**Comment by Gabriel85** [comment]
There is also plenty of free space on the system partition. But I doubt that any of those solutions will fly with LOS anyways..

**Comment by vladimiroltean** [comment]
Rashed posted in the Slack group a link to this script: https://gist.github.com/x86cpu/374b800019a20ca3d55afda39f505a0b
It shaves off 500MB from the end of system.img and creates a vendor.img in that free space.
On the one hand, current lineage-15.1 with nano OpenGapps occupies 1.4GB of the system partition (out of 3.5GB total). The 1.4GB figure includes the /system/vendor folder. So if we go this route, we might as well dedicate a full 1GB for the vendor.img for "future-proofing".

**Comment by Gabriel85** [comment]
Yeah, something like that is exactly what I thought of. It's practicable and the risk would be minimal, but:
1. it would make it harder to switch back to the stock ROM and to switch to a custom ROM in the first place
2. I highly doubt that the LOS guys would accept something like that 
3. it seems to me that the benefit for end-user would be 0

It only really would be feasible to make the whole thing optional in the first place. And I can't see any good reason why somebody even would want to install something like that. Or did I miss any additional benefit of having a separate vendor partition?

**Comment by vladimiroltean** [comment]
I don't think it has any immediate benefit, no. That's why I delayed taking an action for it until now.
I see having a vendor image as a possibility to unlock some of the hardware's potential. From the VNDK/Treble perspective, it is a good thing that the hardware has relatively fewer HALs than a phone (limited RIL, no fingerprint, NFC, whatever) because there's less moving parts => less opportunity for breakage.
But now, since we are able to compile most of the HALs with the VNDK (see #11), the next logical step is to flash a GSI to finally estimate what works and what not. Having a dedicated vendor image is a requirement for that, AFAIK.
Furthermore, why flash a GSI? Mostly for the novelty and the technical challenges, to be honest. If it turns out practicable, I'd say we make the necessary efforts to ship this. If not, at least we have a stronger argument to leave it alone.

**Comment by vladimiroltean** [comment]
The route I'd take to do this is:
* Modify the partition table by hand on my backed-up YTX703L disk image.
* Retrieve the original and the modified partition tables as `gpt.bin` files via the `sgdisk --backup=gpt.bin` command.
* Create a TWRP-flashable zip that applies either the stock or the vendor-enabled partition table via the `sgdisk --replicate=gpt.bin` command.
* Force the kernel to reload the partition table (`partprobe`).

This way, at least we don't run the script on-device and it should be safe to go back and forth, and even to flash the same zip multiple times without having weird effects.

**Comment by vladimiroltean** [comment]
Created the following pull requests to track this:
* https://github.com/Lenovo-YTX703-Devel/android_device_lenovo_YTX703-common/pull/35
* https://github.com/Lenovo-YTX703-Devel/android_kernel_lenovo_msm8976/pull/18
* https://github.com/Lenovo-YTX703-Devel/lenovo_YTX703_TWRP_zips/pull/3

Who are the lucky testers?

**Comment by vladimiroltean** [comment]
Treble is a joke for non-{msm8996,msm8998} devices. Our device is proudly "all about that bass" (https://www.youtube.com/watch?v=7PCkvCPvDXk).
